# Generated by Django 5.2.3 on 2025-07-31 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_orgao', models.CharField(max_length=50)),
                ('Numero_officio', models.CharField(blank=True, max_length=50, null=True)),
                ('Numero_Processo', models.CharField(blank=True, max_length=50, null=True)),
                ('Especie', models.CharField(blank=True, max_length=50, null=True)),
                ('Objeto', models.TextField(blank=True, null=True)),
                ('Direcionamento', models.CharField(blank=True, max_length=100, null=True)),
                ('Anexo', models.FileField(blank=True, null=True, upload_to='anexos/')),
                ('Prazo_Resposta', models.DateField(blank=True, null=True)),
                ('Data_Prazo', models.DateField(blank=True, null=True)),
                ('Monitoramento', models.CharField(blank=True, max_length=50, null=True)),
                ('Indexacao', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
