# Generated by Django 5.2.3 on 2025-07-31 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmodel',
            name='Data_Monitoramento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='Direcionamento',
            field=models.CharField(blank=True, choices=[('Administração, Receita e Tributação', 'Administração, Receita e Tributação'), ('Agricultura, Abastecimento e Pesca', 'Agricultura, Abastecimento e Pesca'), ('Comunicação Social', 'Comunicação Social'), ('Desenvolvimento Social', 'Desenvolvimento Social'), ('Direitos dos Animais', 'Direitos dos Animais'), ('Educação, Cultura, Inclusão, Ciência e Tecnologia', 'Educação, Cultura, Inclusão, Ciência e Tecnologia'), ('Esporte, Lazer e Turismo', 'Esporte, Lazer e Turismo'), ('Finanças', 'Finanças'), ('Gabinete', 'Gabinete'), ('Gestão, Inovação e Tecnologia', 'Gestão, Inovação e Tecnologia'), ('Governança e Sustentabilidade', 'Governança e Sustentabilidade'), ('Infraestrutura', 'Infraestrutura'), ('Meio Ambiente', 'Meio Ambiente'), ('Mulher', 'Mulher'), ('Transporte e Serviços Públicos', 'Transporte e Serviços Públicos'), ('Obras Públicas', 'Obras Públicas'), ('Planejamento', 'Planejamento'), ('Relações Institucionais', 'Relações Institucionais'), ('Saúde', 'Saúde'), ('Segurança e Ordem Pública', 'Segurança e Ordem Pública'), ('Transparência e Integridade', 'Transparência e Integridade'), ('Urbanismo', 'Urbanismo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='Especie',
            field=models.CharField(blank=True, choices=[('Auditoria', 'Auditoria'), ('Monitoramento', 'Monitoramento'), ('Solicitação', 'Solicitação'), ('Representação', 'Representação'), ('Outros:\xa0Especifica', 'Outros:\xa0Especifica')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='Monitoramento',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='Prazo_Resposta',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True),
        ),
    ]
