# Generated by Django 5.2.3 on 2025-09-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_appmodel_data_monitoramento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmodel',
            name='OBSERVAÇÃO',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appmodel',
            name='TAREFAS',
            field=models.TextField(blank=True, null=True),
        ),
    ]
