# Generated by Django 5.2.3 on 2025-09-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_appmodel_observação_appmodel_tarefas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmodel',
            name='Especie',
            field=models.CharField(blank=True, choices=[('Auditoria', 'Auditoria'), ('Monitoramento', 'Monitoramento'), ('Solicitação', 'Solicitação'), ('Representação', 'Representação'), ('Outros: Especifica', 'Outros: Especifica')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='Monitoramento',
            field=models.CharField(blank=True, choices=[('Mensal', 'Mensal'), ('Trimestral', 'Trimestral'), ('Semestral', 'Semestral'), ('Anual', 'Anual'), ('Não monitorado', 'Não monitorado')], max_length=20, null=True),
        ),
    ]
