# Generated by Django 5.2.3 on 2025-09-16 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_appmodel_especie_alter_appmodel_monitoramento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appmodel',
            name='Anexo',
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos/')),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='App.appmodel')),
            ],
        ),
    ]
