# Generated by Django 5.2.3 on 2025-09-18 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_remove_appmodel_anexo_anexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appmodel',
            name='TAREFAS',
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('concluida', models.BooleanField(default=False)),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='App.appmodel')),
            ],
        ),
    ]
